name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: [ self-hosted, forest ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cd src && make build